server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sp_db
    username: root
    password:
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true

school-plus:
  url: http://localhost:8080
  auth-config:
    access-token:
      lifetime: 5m
    refresh-token:
      lifetime: 8h
    purging-refresh-tokens-cron: "* * 0/6 * * *"