package com.schoolplus.office.web.models;

public enum DomainAction {
    /*
     * Announcement
     */
    CREATE_ANNOUNCEMENT,
    READ_ANNOUNCEMENTS,
    READ_ANNOUNCEMENT,
    UPDATE_ANNOUNCEMENT,
    UPLOAD_ANNOUNCEMENT_IMAGE,
    DELETE_ANNOUNCEMENT_IMAGE,
    DELETE_ANNOUNCEMENT,

    /*
     * Appointment
     */
    READ_APPOINTMENT,
    READ_APPOINTMENTS,
    CREATE_APPOINTMENT,
    UPDATE_APPOINTMENT,
    DELETE_APPOINTMENT,

    /*
     * Classroom
     */
    READ_CLASSROOMS,
    READ_CLASSROOM,
    CREATE_CLASSROOM,
    UPDATE_CLASSROOM,
    DELETE_CLASSROOM,

    /*
     * Continuity
     */
    READ_CONTINUITIES,
    READ_CONTINUITIES_BY_SYLLABUS,
    READ_CONTINUITIES_BY_CLASSROOM,
    READ_CONTINUITIES_BY_STUDENT,
    READ_CONTINUITIES_BY_ORGANIZATION,
    READ_CONTINUITY,
    CREATE_CONTINUITY,
    UPDATE_CONTINUITY,
    DELETE_CONTINUITY,

    /*
     * Exam
     */
    READ_EXAMS,
    READ_EXAMS_BY_ORGANIZATION,
    READ_EXAM,
    CREATE_EXAM,
    UPDATE_EXAM,
    DELETE_EXAM,

    /*
     * Exam Type
     */
    READ_EXAM_TYPE,
    READ_EXAM_TYPES,
    READ_EXAM_TYPES_BY_ORGANIZATION,
    CREATE_EXAM_TYPE,
    UPDATE_EXAM_TYPE,
    DELETE_EXAM_TYPE,

    /*
     * Exam Skeleton
     */
    READ_EXAM_SKELETON,
    READ_EXAM_SKELETONS,
    READ_EXAM_SKELETONS_BY_ORGANIZATION,
    CREATE_EXAM_SKELETON,
    UPDATE_EXAM_SKELETON,
    DELETE_EXAM_SKELETON,

    /*
     * Exam Result
     */
    READ_EXAM_RESULT,
    READ_EXAM_RESULTS,
    READ_EXAM_RESULTS_BY_ORGANIZATION,
    READ_EXAM_RESULTS_BY_STUDENT,
    READ_EXAM_RESULTS_BY_CLASSROOM,
    READ_EXAM_RESULTS_BY_GRADE,
    CREATE_EXAM_RESULT,
    UPDATE_EXAM_RESULT,
    DELETE_EXAM_RESULT,

    /*
     * Exam Result Item
     */
    READ_EXAM_RESULT_ITEM,
    UPDATE_EXAM_RESULT_ITEM,

    /*
     * Grade
     */
    READ_GRADES,
    READ_GRADE,
    CREATE_GRADE,
    UPDATE_GRADE,
    DELETE_GRADE,

    /*
     * Homework
     */
    READ_HOMEWORKS,
    READ_HOMEWORKS_BY_CLASSROOM,
    READ_HOMEWORKS_BY_TEAHCER,
    READ_HOMEWORKS_BY_SYLLABUS,
    READ_HOMEWORK,
    CREATE_HOMEWORK,
    UPDATE_HOMEWORK,
    DELETE_HOMEWORK,

    /*
     * Lesson
     */
    READ_LESSON,
    READ_LESSONS,
    READ_LESSONS_BY_ORGANIZATION,
    CREATE_LESSON,
    UPDATE_LESSON,
    DELETE_LESSON,

    /*
     * Organization
     */
    READ_ORGANIZATION,
    READ_ORGANIZATIONS,
    CREATE_ORGANIZATION,
    UPDATE_ORGANIZATION,
    DELETE_ORGANIZATION,

    /*
     * Parent
     */
    READ_PARENT,
    CREATE_PARENT,
    UPDATE_PARENT,

    /*
     * Personal Homework
     */
    READ_PERSONAL_HOMEWORK,
    READ_PERSONAL_HOMEWORK_BY_STUDENT,
    READ_PERSONAL_HOMEWORK_BY_TEACHER,
    READ_PERSONAL_HOMEWORK_BY_LESSON,
    CREATE_PERSONAL_HOMEWORK,
    UPDATE_PERSONAL_HOMEWORK,
    DELETE_PERSONAL_HOMEWORK,

    /*
     * Student
     */
    READ_STUDENT,
    CREATE_STUDENT,
    UPDATE_STUDENT,

    /*
     * Support Request
     */
    READ_SUPPORT_REQUEST,
    READ_SUPPORT_REQUEST_BY_ORGANIZATION,
    READ_SUPPORT_REQUEST_BY_ORGANIZATION_AND_UNANSWERED,
    READ_SUPPORT_REQUEST_BY_ORGANIZATION_AND_ANSWERED,
    READ_SUPPORT_REQUEST_BY_ORGANIZATION_AND_ANONYMOUS,
    READ_SUPPORT_REQUEST_BY_ORGANIZATION_AND_NAMED,
    READ_SUPPORT_REQUEST_BY_ORGANIZATION_AND_USER,
    UPDATE_SUPPORT_REQUEST,
    DELETE_SUPPORT_REQUEST,

    /*
     * Support Thread
     */
    CREATE_SUPPORT_THREAD,
    DELETE_SUPPORT_THREAD,

    /*
     * Syllabus
     */
    READ_SYLLABUS,
    READ_SYLLABUSES,
    READ_SYLLABUS_BY_CLASSROOM,
    READ_SYLLABUS_BY_LESSON,
    READ_SYLLABUS_BY_TEACHER,
    READ_SYLLABUS_BY_ORGANIZATION,
    CREATE_SYLLABUS,
    DELETE_SYLLABUS,
    UPDATE_SYLLABUS,

    /*
     * Teacher
     */
    READ_TEACHER,
    CREATE_TEACHER,
    UPDATE_TEACHER,

    /*
     * Teaching Subject
     */
    READ_TEACHING_SUBJECT,
    READ_TEACHING_SUBJECTS,
    CREATE_TEACHING_SUBJECT,
    UPDATE_TEACHING_SUBJECT,
    DELETE_TEACHING_SUBJECT,

    /*
     * USER
     */
    READ_USER,
    READ_USERS,
    CREATE_USER,
    UPDATE_USER,
    DELETE_USER,

    /*
     * Authentication
     */
    LOGIN_SUCCESSFULLY,
    LOGOUT_SUCCESSFULLY,

    /*
     * User Info
     */
    READ_USERINFO,

    /*
     * Grade Category
     */
    READ_GRADE_CATEGORY,
    CREATE_GRADE_CATEGORY,
    UPDATE_GRADE_CATEGORY,
    DELETE_GRADE_CATEGORY,

}
